import { notFound } from "next/navigation";
import Link from "next/link";
import { AppShell } from "@/components/product/AppShell";
import { Brand } from "@/components/product/Brand";
import { PageHeader, EmptyState, StatusBadge } from "@/components/product/ui";
import { DashboardView, FormRows, ClientRows } from "@/components/product/WorkspaceViews";
import { FormBuilder } from "@/app/forms/[formId]/build/FormBuilder";
import { FormPreview } from "@/app/forms/[formId]/preview/FormPreview";
import { NewFormForm } from "@/app/forms/new/NewFormForm";
import { CoachingProfileForm } from "@/components/product/CoachingProfileForm";
import { ConnectionsClient } from "@/app/settings/connections/ConnectionsClient";
import { CoachBriefPanel } from "@/app/clients/[clientId]/submissions/[submissionId]/CoachBriefPanel";
import { DeleteClientButton } from "@/app/clients/[clientId]/DeleteClientButton";
import { createBlankOnboardingSchema } from "@/lib/forms/blank-schema";
import { PublicDesignPreview } from "./public-preview";

const screens = ["dashboard", "forms", "create", "builder", "preview", "public", "clients", "client", "submission", "settings", "profile", "setup", "connections", "states"];
const forms = [{ id: "design-sample", name: "Foundations onboarding", status: "published", versionNumber: 2, updatedAt: "2026-09-18" }, { id: "design-draft", name: "Online coaching · First steps", status: "draft", versionNumber: null, updatedAt: "2026-09-20" }];
const clients = [{ client: { id: "design-client", fullName: "Alex Morgan", email: "alex@example.com" }, latestFormName: "Foundations onboarding", latestReviewStatus: "needs_review", latestSubmittedAt: "2026-09-21" }, { client: { id: "design-client-2", fullName: "Sam Rivera", email: "sam@example.com" }, latestFormName: "Foundations onboarding", latestReviewStatus: "new", latestSubmittedAt: "2026-09-20" }, { client: { id: "design-client-3", fullName: "Jamie Chen", email: "jamie@example.com" }, latestFormName: "Foundations onboarding", latestReviewStatus: "reviewed", latestSubmittedAt: "2026-09-19" }];
const branding = { businessName: "Eman Coaching", coachName: "Eman", primaryColor: null };

export default async function DesignPage({ searchParams }: { searchParams: Promise<{ screen?: string; state?: string }> }) {
  if (process.env.NODE_ENV === "production") notFound();
  const query = await searchParams;
  const screen = screens.includes(query.screen || "") ? query.screen! : "dashboard";
  const empty = query.state === "empty";
  const schema = createBlankOnboardingSchema("Foundations onboarding");
  schema.intro.title = "Let's start with you.";
  schema.intro.description = ["Your goals, your routine, your story. These questions help me get to know you before we begin.", "Take your time. There's no perfect answer — just your honest one."];
  schema.sections.splice(1, 0, { id: "goals", key: "goals", title: "What matters to you?", navLabel: "Your goals", position: 1, fields: [
    { id: "goal", key: "goal", type: "single_select", label: "What would you like to work toward?", required: true, position: 0, options: [{label:"Build strength",value:"strength"},{label:"Feel more confident",value:"confidence"},{label:"Find a consistent routine",value:"routine"}] },
    { id: "story", key: "story", type: "long_text", label: "What would progress look like for you?", required: false, position: 1, placeholder: "In your own words…" },
    { id: "pain", key: "pain", type: "boolean", label: "Any current injury or pain you want me to know about?", required: true, position: 2 },
    { id: "pain_detail", key: "pain_detail", type: "long_text", label: "Tell me a little more.", required: true, position: 3, logic: { action: "show", all: [{ fieldKey: "pain", operator: "equals", value: true }] } },
  ] });
  let content;
  if (screen === "dashboard") content = <DashboardView coachName="Eman" forms={empty ? [] : forms} clients={empty ? [] : clients} />;
  else if (screen === "builder") content = <FormBuilder formId="design-sample" formName="Foundations onboarding" slug="design-sample" status="draft" activeVersionNumber={null} initialSchema={schema} initialRevision={3} initialIdentity={{ fullNameFieldKey: "full_name", emailFieldKey: "email" }} initialReviewRules={null} versions={[]} branding={branding} initialMessages={[{ id:"you-1", role:"user", content:"Shorten the opening and add a goals section." },{ id:"proposal-message",role:"assistant",content:"I'll shorten the opening and add a goals section.",changeSetId:"design-proposal" }]} initialChangeSets={[{ id:"design-proposal",status:"proposed",summary:"+ Add What matters to you?\n+ Add 3 questions",details:["Updated intro: Let's start with you.","Added section: What matters to you?","Added question: What would you like to work toward?"],baseDraftRevision:3 }]} />;
  else if (screen === "preview") content = <><div className="px-6 py-4 border-b border-line"><Link href="?screen=builder" className="text-link">← Back to editor</Link><p className="text-sm text-muted mt-2">Draft preview. No answers will be saved.</p></div><FormPreview schema={schema} branding={branding}/></>;
  else if (screen === "public") content = <PublicDesignPreview schema={schema} branding={branding}/>;
  else if (screen === "setup") content = <main className="setup-page"><Brand/><div className="setup-layout"><section><p className="eyebrow">Coach setup · Your foundation</p><h1>A workspace that understands your coaching.</h1><p>Tell us who you help and how you work. Your Agent uses this context to build more thoughtful onboarding.</p><p className="setup-note">You can refine these details anytime in your coaching profile.</p></section><CoachingProfileForm mode="setup" initial={{coachName:"Eman"}}/></div></main>;
  else content = <main className="workspace-page">
    {screen === "forms" && <><PageHeader eyebrow="Your onboarding library" title="Forms" description="Thoughtful questions. A better start for every client." action={<Link className="button button-primary" href="?screen=create">+ Create onboarding</Link>}/><div className="list-toolbar"><nav className="filter-tabs"><Link aria-current="page" href="?screen=forms">All forms</Link><Link href="?screen=forms&state=empty">Draft</Link><Link href="?screen=forms">Published</Link></nav><span className="text-sm text-muted">{empty?0:forms.length} forms</span></div>{empty?<EmptyState title="Your first hello starts here." description="Build an onboarding that fits your coaching." href="?screen=create" action="Create your first onboarding"/>:<FormRows rows={forms}/>}</>}
    {screen === "create" && <><PageHeader eyebrow="Forms / New onboarding" title="A thoughtful start." description="Choose how you want to build your client onboarding."/><div className="create-layout"><NewFormForm/><aside><p className="eyebrow">Your form, your approach</p><h2>Start with what matters.</h2><p>Collect the context you need before your first conversation.</p><ol className="workflow-list"><li>Choose a starting point</li><li>Refine your questions</li><li>Preview and publish</li></ol></aside></div></>}
    {screen === "clients" && <><PageHeader eyebrow="People, not paperwork" title="Clients" description="Get to know the person behind every submission."/><div className="list-toolbar"><input aria-label="Search clients" placeholder="Search name or email" className="border border-line bg-surface px-4 py-2"/><nav className="filter-tabs"><Link aria-current="page" href="?screen=clients">All</Link><Link href="?screen=clients">New</Link><Link href="?screen=clients">Needs review</Link><Link href="?screen=clients">Reviewed</Link></nav></div>{empty?<EmptyState title="Your next client starts here." description="Clients appear after completing a published onboarding." href="?screen=forms" action="Go to forms"/>:<ClientRows rows={clients}/>}</>}
    {screen === "client" && <><Link className="text-link" href="?screen=clients">← All clients</Link><div className="client-profile-head"><div><p className="eyebrow">Client profile</p><h1>Alex Morgan</h1><p>alex@example.com</p><p>+1 604 555 0148</p></div><DeleteClientButton clientId="design-client" name="Alex Morgan"/></div><div className="section-heading"><h2>Onboarding history</h2></div><ul className="data-list"><li><Link className="data-row" href="?screen=submission"><div className="row-main"><strong>Foundations onboarding</strong><small>Version 2 · September 21, 2026</small></div><StatusBadge status="needs_review"/></Link></li></ul></>}
    {screen === "submission" && <><Link className="text-link" href="?screen=client">← Back to Alex Morgan</Link><PageHeader eyebrow="Client onboarding" title="Alex Morgan" description="Foundations onboarding · Version 2 · September 21, 2026" action={<StatusBadge status="needs_review"/>}/><nav className="submission-jumps"><a href="#submitted-information">Original answers</a><a href="#review-flags">Review Flags</a><a href="#coach-brief">AI Coach Brief</a></nav><div className="submission-layout"><section id="submitted-information" className="original-answers"><p className="eyebrow">01 · Client-provided information</p><h2 className="font-display text-3xl mt-2">Original answers</h2>{[["Your goals","What would you like to work toward?","Build strength and feel more confident."],["Your routine","What does your week look like?","I can train on Monday, Wednesday, and Saturday. I work at a desk most days."],["Training experience","Tell me about your training so far.","I've tried the gym a few times but want a consistent routine."],["Things to discuss","Any current injury or pain?","My right shoulder sometimes feels uncomfortable overhead."]].map(([title,label,answer])=><section key={title} className="mt-8"><h3 className="font-display text-xl">{title}</h3><dl className="mt-4 border-b border-line pb-4"><dt className="text-muted text-sm">{label}</dt><dd className="mt-2">{answer}</dd></dl></section>)}</section><aside className="submission-context"><section id="review-flags" className="review-flags"><p className="eyebrow">02 · Rule-based Review Flags</p><h2 className="font-display text-3xl mt-2">Coach review needed</h2><p className="mt-4 font-medium">Current injury or pain reported</p><p className="text-sm text-muted mt-2">Based on: Any current injury or pain?</p></section><CoachBriefPanel submissionId="design-submission" initial={{status:"complete",payload:{summary:{text:"Alex wants to build strength and confidence with a routine that fits around desk-based work.",sourceFieldKeys:["goal","routine"]},training:[{text:"Some gym experience. Available Monday, Wednesday, and Saturday.",sourceFieldKeys:["routine"]}],thingsToReview:[{text:"Ask Alex to describe the shoulder discomfort they mentioned.",sourceFieldKeys:["pain"]}],kickoffTopics:[{text:"What would a consistent first month look like to you?",sourceFieldKeys:["goal"]}]}}} labels={{goal:"Your goals",routine:"Your weekly routine",pain:"Current injury or pain"}}/></aside></div></>}
    {screen === "profile" && <><PageHeader eyebrow="Settings" title="Coaching profile" description="Give your Agent context about who you coach and how you work."/><CoachingProfileForm mode="edit" initial={{businessName:"Eman Coaching",coachName:"Eman",targetClientDescription:"People building confidence and a consistent routine in the gym.",requiresHealthScreening:true}}/></>}
    {screen === "settings" && <><PageHeader eyebrow="Workspace preferences" title="Settings" description="Eman Coaching"/><div className="settings-layout"><div><section className="settings-section"><h2>Your coaching profile</h2><p>The context behind your onboarding.</p><Link className="button" href="?screen=profile">Edit coaching profile ↗</Link></section><section className="settings-section"><h2>Connected tools</h2><p>Manage Google Sheets, signed webhooks, and delivery history.</p><Link className="button" href="?screen=connections">Manage connections ↗</Link></section><section className="settings-section"><h2>Your workspace data</h2><p>Export profile, forms, clients, submissions, flags, and briefs. Secrets are excluded.</p><button className="button" disabled>Export workspace · Sample</button></section></div><aside className="settings-aside"><h2>A workspace that fits you.</h2><p>Updating your coaching profile does not change published forms.</p></aside></div></>}
    {screen === "connections" && <><PageHeader eyebrow="Your workflow" title="Connections" description="Keep your client context connected to the tools you use."/><ConnectionsClient googleConfigured integrations={empty?[]:[{id:"design-google",type:"google_sheets",name:"Google Sheets",status:"connected",lastError:null,updatedAt:"2026-09-21",spreadsheetId:"sample",spreadsheetTitle:"Client onboarding",endpointUrl:null},{id:"design-hook",type:"webhook",name:"Coaching records",status:"error",lastError:"Endpoint unavailable",updatedAt:"2026-09-21",spreadsheetId:null,spreadsheetTitle:null,endpointUrl:"https://example.com/onboarding"}]} deliveries={empty?[]:[{id:"design-delivery",integrationId:"design-hook",submissionId:"design-submission",eventType:"submission.created",status:"failed",attemptCount:2,lastAttemptAt:"2026-09-21",lastError:"Endpoint did not respond.",clientId:"design-client"}]}/></>}
    {screen === "states" && <><PageHeader eyebrow="Component reference" title="Clear at every step." description="Sample feedback, status, loading, and destructive states."/><div className="flex gap-3 flex-wrap mb-8">{["draft","published","new","needs_review","reviewed","connected","disabled","error","failed","proposed","applied","superseded"].map(status=><StatusBadge key={status} status={status}/>)}</div><div className="settings-section"><h2>Loading a list</h2><div className="skeleton h-16 mt-4"/><div className="skeleton h-16 mt-4"/></div><div className="review-flags mb-6" role="alert"><h2>Another session changed this draft.</h2><p className="mt-2">Reload the latest version before continuing. Your proposal has not been applied.</p></div><div className="connection-feedback mb-6" role="status">Your onboarding is published. The client link is ready to share.</div><EmptyState title="No deliveries yet." description="New submissions sent to connected tools will appear here."/><div className="mt-6"><DeleteClientButton clientId="design-client" name="Alex Morgan"/></div></>}
  </main>;
  const activePath = screen === "builder" ? "/forms/design/build" : ["forms","create","preview"].includes(screen) ? "/forms" : ["client","clients","submission"].includes(screen) ? "/clients" : screen === "connections" ? "/settings/connections" : ["profile","settings","states"].includes(screen) ? "/settings" : "/dashboard";
  return <><div className="design-review-bar"><span>Design review · Sample data only</span><form><label htmlFor="design-screen" className="sr-only">Screen</label><select id="design-screen" name="screen" defaultValue={screen}>{screens.map(name=><option key={name}>{name}</option>)}</select><button className="button" type="submit">View</button></form><Link href={"?screen="+screen+"&state="+(empty?"populated":"empty")}>{empty?"Populated":"Empty"} state</Link><Link href="/">Landing ↗</Link><Link href="/login">Login ↗</Link><Link href="/signup">Signup ↗</Link></div>{["public","setup"].includes(screen)?content:<AppShell businessName="Eman Coaching" activePath={activePath}>{content}</AppShell>}</>;
}
