export type FieldMapRow = {
  field_key: string;
  client_label: string;
  section: string;
  data_type: string;
  required: string;
  possible_values: string;
  CRM_destination: string;
  notes: string;
};

export const RESPONSE_COLUMNS = [
  "submission_id",
  "submitted_at",
  "schema_version",
  "full_name",
  "email",
  "phone",
  "date_of_birth",
  "sex",
  "height_value",
  "height_unit",
  "height_inches",
  "weight_value",
  "weight_unit",
  "occupation",
  "activity_level",
  "average_steps",
  "current_injuries",
  "current_injury_details",
  "previous_injuries",
  "previous_injury_details",
  "surgeries",
  "surgery_details",
  "exercise_restrictions",
  "exercise_restriction_details",
  "medical_conditions",
  "medical_condition_details",
  "medications",
  "medication_details",
  "pregnancy_considerations",
  "health_additional_notes",
  "health_acknowledgement",
  "training_experience",
  "current_training_days",
  "current_training_description",
  "structured_program_experience",
  "confident_exercises",
  "uncertain_exercises",
  "disliked_exercises",
  "preferred_exercises",
  "training_days_available",
  "available_days",
  "session_duration",
  "training_location",
  "gym_name",
  "equipment_access",
  "in_person_location_preference",
  "primary_goal",
  "secondary_goals",
  "goal_changes",
  "goal_change_details",
  "current_eating",
  "meals_per_day",
  "typical_breakfast",
  "typical_lunch",
  "typical_dinner",
  "typical_snacks",
  "typical_drinks",
  "calorie_tracking",
  "current_calories",
  "current_protein",
  "current_carbs",
  "current_fat",
  "food_allergies",
  "food_allergy_details",
  "dietary_restrictions",
  "dietary_restriction_details",
  "preferred_foods",
  "disliked_foods",
  "takeout_frequency",
  "water_intake",
  "alcohol_frequency",
  "weight_change_history",
  "weight_change_details",
  "sleep_duration",
  "sleep_quality",
  "stress_level",
  "stress_sources",
  "work_schedule",
  "work_schedule_details",
  "schedule_challenges",
  "progress_methods",
  "progress_photos",
  "feedback_preference",
  "consistency_challenges",
  "fall_off_causes",
  "coaching_dislikes",
  "coaching_concerns",
  "additional_notes",
  "accuracy_acknowledgement",
  "coach_review_needed",
  "health_flag",
  "health_flag_reasons",
  "onboarding_status",
] as const;

export const CLIENT_COLUMNS = [
  "submission_id",
  "submitted_at",
  "full_name",
  "email",
  "phone",
  "date_of_birth",
  "current_weight",
  "primary_goal",
  "training_experience",
  "training_days_available",
  "training_location",
  "health_flag",
  "sleep_duration",
  "stress_level",
  "feedback_preference",
  "onboarding_status",
  "coach_notes",
  "coach_review_needed",
] as const;

export const FIELD_MAP_COLUMNS = [
  "field_key",
  "client_label",
  "section",
  "data_type",
  "required",
  "possible_values",
  "CRM_destination",
  "notes",
] as const;

export const FIELD_MAP: FieldMapRow[] = [
  { field_key: "submission_id", client_label: "Submission ID", section: "system", data_type: "uuid", required: "TRUE", possible_values: "", CRM_destination: "onboarding.submission_id", notes: "Server generated" },
  { field_key: "submitted_at", client_label: "Submitted at", section: "system", data_type: "datetime", required: "TRUE", possible_values: "ISO-8601 UTC", CRM_destination: "onboarding.submitted_at", notes: "Server generated" },
  { field_key: "schema_version", client_label: "Schema version", section: "system", data_type: "string", required: "TRUE", possible_values: "onboarding_v1", CRM_destination: "onboarding.schema_version", notes: "" },
  { field_key: "full_name", client_label: "Full name", section: "about", data_type: "string", required: "TRUE", possible_values: "", CRM_destination: "clients.full_name", notes: "" },
  { field_key: "email", client_label: "Email", section: "about", data_type: "email", required: "TRUE", possible_values: "", CRM_destination: "clients.email", notes: "" },
  { field_key: "phone", client_label: "Phone / WhatsApp", section: "about", data_type: "string", required: "TRUE", possible_values: "", CRM_destination: "clients.phone", notes: "" },
  { field_key: "date_of_birth", client_label: "Date of birth", section: "about", data_type: "date", required: "TRUE", possible_values: "YYYY-MM-DD", CRM_destination: "clients.date_of_birth", notes: "" },
  { field_key: "sex", client_label: "Sex", section: "about", data_type: "enum", required: "TRUE", possible_values: "female|male|prefer_not_to_say", CRM_destination: "clients.sex", notes: "" },
  { field_key: "height_value", client_label: "Height", section: "about", data_type: "number", required: "TRUE", possible_values: "", CRM_destination: "clients.height_value", notes: "cm or feet depending on unit" },
  { field_key: "height_unit", client_label: "Height unit", section: "about", data_type: "enum", required: "TRUE", possible_values: "cm|ft_in", CRM_destination: "clients.height_unit", notes: "" },
  { field_key: "height_inches", client_label: "Height inches", section: "about", data_type: "number", required: "FALSE", possible_values: "0-11.9", CRM_destination: "clients.height_inches", notes: "Used when height_unit is ft_in" },
  { field_key: "weight_value", client_label: "Current bodyweight", section: "about", data_type: "number", required: "TRUE", possible_values: "", CRM_destination: "clients.weight_value", notes: "" },
  { field_key: "weight_unit", client_label: "Weight unit", section: "about", data_type: "enum", required: "TRUE", possible_values: "lb|kg", CRM_destination: "clients.weight_unit", notes: "" },
  { field_key: "occupation", client_label: "Occupation", section: "about", data_type: "string", required: "FALSE", possible_values: "", CRM_destination: "clients.occupation", notes: "" },
  { field_key: "activity_level", client_label: "Normal workday activity", section: "about", data_type: "enum", required: "TRUE", possible_values: "mostly_sitting|mix_sitting_walking|mostly_standing|physically_active|very_physically_demanding", CRM_destination: "lifestyle.activity_level", notes: "" },
  { field_key: "average_steps", client_label: "Approximate daily steps", section: "about", data_type: "enum", required: "TRUE", possible_values: "under_3000|3000_5000|5000_8000|8000_10000|10000_plus|unknown", CRM_destination: "lifestyle.average_steps", notes: "" },
  { field_key: "current_injuries", client_label: "Current injuries, pain or limitations", section: "health", data_type: "enum", required: "TRUE", possible_values: "yes|no", CRM_destination: "health.current_injuries", notes: "Review flag input. Not a diagnosis." },
  { field_key: "current_injury_details", client_label: "Current injury details", section: "health", data_type: "text", required: "conditional", possible_values: "", CRM_destination: "health.current_injury_details", notes: "Required if yes" },
  { field_key: "previous_injuries", client_label: "Significant previous injuries", section: "health", data_type: "enum", required: "TRUE", possible_values: "yes|no", CRM_destination: "health.previous_injuries", notes: "" },
  { field_key: "previous_injury_details", client_label: "Previous injury details", section: "health", data_type: "text", required: "conditional", possible_values: "", CRM_destination: "health.previous_injury_details", notes: "" },
  { field_key: "surgeries", client_label: "Significant surgeries", section: "health", data_type: "enum", required: "TRUE", possible_values: "yes|no", CRM_destination: "health.surgeries", notes: "" },
  { field_key: "surgery_details", client_label: "Surgery details", section: "health", data_type: "text", required: "conditional", possible_values: "", CRM_destination: "health.surgery_details", notes: "" },
  { field_key: "exercise_restrictions", client_label: "Healthcare professional asked to limit exercise", section: "health", data_type: "enum", required: "TRUE", possible_values: "yes|no", CRM_destination: "health.exercise_restrictions", notes: "" },
  { field_key: "exercise_restriction_details", client_label: "Exercise restriction details", section: "health", data_type: "text", required: "conditional", possible_values: "", CRM_destination: "health.exercise_restriction_details", notes: "" },
  { field_key: "medical_conditions", client_label: "Medical conditions affecting exercise or nutrition", section: "health", data_type: "enum", required: "TRUE", possible_values: "yes|no|unsure", CRM_destination: "health.medical_conditions", notes: "" },
  { field_key: "medical_condition_details", client_label: "Medical condition details", section: "health", data_type: "text", required: "conditional", possible_values: "", CRM_destination: "health.medical_condition_details", notes: "" },
  { field_key: "medications", client_label: "Medications that may affect training or nutrition", section: "health", data_type: "enum", required: "TRUE", possible_values: "no|yes|prefer_privately", CRM_destination: "health.medications", notes: "" },
  { field_key: "medication_details", client_label: "Medication details", section: "health", data_type: "text", required: "FALSE", possible_values: "", CRM_destination: "health.medication_details", notes: "Optional even if yes" },
  { field_key: "pregnancy_considerations", client_label: "Pregnancy / postpartum considerations", section: "health", data_type: "enum", required: "TRUE", possible_values: "no|yes|not_applicable|prefer_privately", CRM_destination: "health.pregnancy_considerations", notes: "" },
  { field_key: "health_additional_notes", client_label: "Anything else about your health", section: "health", data_type: "text", required: "FALSE", possible_values: "", CRM_destination: "health.additional_notes", notes: "" },
  { field_key: "health_acknowledgement", client_label: "Health professional acknowledgement", section: "health", data_type: "boolean", required: "TRUE", possible_values: "TRUE|FALSE", CRM_destination: "health.acknowledgement", notes: "" },
  { field_key: "training_experience", client_label: "Strength training experience", section: "training", data_type: "enum", required: "TRUE", possible_values: "never|under_3_months|3_6_months|6_12_months|1_2_years|2_plus_years", CRM_destination: "training.experience", notes: "" },
  { field_key: "current_training_days", client_label: "Current training days per week", section: "training", data_type: "integer", required: "TRUE", possible_values: "0-7", CRM_destination: "training.current_days", notes: "" },
  { field_key: "current_training_description", client_label: "What current training looks like", section: "training", data_type: "text", required: "TRUE", possible_values: "", CRM_destination: "training.current_description", notes: "" },
  { field_key: "structured_program_experience", client_label: "Followed a structured program before", section: "training", data_type: "enum", required: "TRUE", possible_values: "yes|no", CRM_destination: "training.structured_program", notes: "" },
  { field_key: "confident_exercises", client_label: "Exercises you feel confident performing", section: "training", data_type: "text", required: "TRUE", possible_values: "", CRM_destination: "training.confident_exercises", notes: "" },
  { field_key: "uncertain_exercises", client_label: "Exercises you struggle with", section: "training", data_type: "text", required: "TRUE", possible_values: "", CRM_destination: "training.uncertain_exercises", notes: "" },
  { field_key: "disliked_exercises", client_label: "Exercises you prefer not to do", section: "training", data_type: "text", required: "FALSE", possible_values: "", CRM_destination: "training.disliked_exercises", notes: "" },
  { field_key: "preferred_exercises", client_label: "Exercises you enjoy", section: "training", data_type: "text", required: "FALSE", possible_values: "", CRM_destination: "training.preferred_exercises", notes: "" },
  { field_key: "training_days_available", client_label: "Realistic training days per week", section: "schedule", data_type: "enum", required: "TRUE", possible_values: "2|3|4|5|6", CRM_destination: "training.days_available", notes: "" },
  { field_key: "available_days", client_label: "Days usually available", section: "schedule", data_type: "json_array", required: "TRUE", possible_values: "monday-sunday", CRM_destination: "training.available_days", notes: "JSON array" },
  { field_key: "session_duration", client_label: "Realistic workout duration", section: "schedule", data_type: "enum", required: "TRUE", possible_values: "30_45|45_60|60_75|75_90|90_plus", CRM_destination: "training.session_duration", notes: "" },
  { field_key: "training_location", client_label: "Where you normally train", section: "schedule", data_type: "enum", required: "TRUE", possible_values: "commercial_gym|apartment_gym|home_gym|home_limited_equipment|other", CRM_destination: "training.location", notes: "" },
  { field_key: "gym_name", client_label: "Gym name", section: "schedule", data_type: "string", required: "FALSE", possible_values: "", CRM_destination: "training.gym_name", notes: "" },
  { field_key: "equipment_access", client_label: "Equipment access", section: "schedule", data_type: "json_array", required: "TRUE", possible_values: "see EQUIPMENT constants", CRM_destination: "training.equipment_access", notes: "JSON array" },
  { field_key: "in_person_location_preference", client_label: "Preferred in-person session location", section: "schedule", data_type: "string", required: "FALSE", possible_values: "", CRM_destination: "training.in_person_location", notes: "Hybrid clients" },
  { field_key: "primary_goal", client_label: "Number one fitness priority", section: "goals", data_type: "text", required: "TRUE", possible_values: "", CRM_destination: "goals.primary", notes: "" },
  { field_key: "secondary_goals", client_label: "Other results to work toward", section: "goals", data_type: "json_array", required: "FALSE", possible_values: "see SECONDARY_GOALS", CRM_destination: "goals.secondary", notes: "JSON array" },
  { field_key: "goal_changes", client_label: "Goals changed since last conversation", section: "goals", data_type: "enum", required: "TRUE", possible_values: "yes|no", CRM_destination: "goals.changed", notes: "" },
  { field_key: "goal_change_details", client_label: "What changed", section: "goals", data_type: "text", required: "conditional", possible_values: "", CRM_destination: "goals.change_details", notes: "" },
  { field_key: "current_eating", client_label: "Current eating structure", section: "nutrition", data_type: "enum", required: "TRUE", possible_values: "very_structured|somewhat_structured|inconsistent|mostly_convenient|unsure", CRM_destination: "nutrition.eating_structure", notes: "No calorie prescription" },
  { field_key: "meals_per_day", client_label: "Meals per day", section: "nutrition", data_type: "number", required: "TRUE", possible_values: "1-10", CRM_destination: "nutrition.meals_per_day", notes: "" },
  { field_key: "typical_breakfast", client_label: "Typical breakfast", section: "nutrition", data_type: "text", required: "TRUE", possible_values: "", CRM_destination: "nutrition.breakfast", notes: "" },
  { field_key: "typical_lunch", client_label: "Typical lunch", section: "nutrition", data_type: "text", required: "TRUE", possible_values: "", CRM_destination: "nutrition.lunch", notes: "" },
  { field_key: "typical_dinner", client_label: "Typical dinner", section: "nutrition", data_type: "text", required: "TRUE", possible_values: "", CRM_destination: "nutrition.dinner", notes: "" },
  { field_key: "typical_snacks", client_label: "Typical snacks", section: "nutrition", data_type: "text", required: "FALSE", possible_values: "", CRM_destination: "nutrition.snacks", notes: "" },
  { field_key: "typical_drinks", client_label: "Typical drinks", section: "nutrition", data_type: "text", required: "FALSE", possible_values: "", CRM_destination: "nutrition.drinks", notes: "" },
  { field_key: "calorie_tracking", client_label: "Currently tracking calories or macros", section: "nutrition", data_type: "enum", required: "TRUE", possible_values: "yes|no", CRM_destination: "nutrition.tracking", notes: "" },
  { field_key: "current_calories", client_label: "Current calories", section: "nutrition", data_type: "string", required: "FALSE", possible_values: "", CRM_destination: "nutrition.calories", notes: "" },
  { field_key: "current_protein", client_label: "Current protein", section: "nutrition", data_type: "string", required: "FALSE", possible_values: "", CRM_destination: "nutrition.protein", notes: "" },
  { field_key: "current_carbs", client_label: "Current carbohydrates", section: "nutrition", data_type: "string", required: "FALSE", possible_values: "", CRM_destination: "nutrition.carbs", notes: "" },
  { field_key: "current_fat", client_label: "Current fat", section: "nutrition", data_type: "string", required: "FALSE", possible_values: "", CRM_destination: "nutrition.fat", notes: "" },
  { field_key: "food_allergies", client_label: "Food allergies or intolerances", section: "nutrition", data_type: "enum", required: "TRUE", possible_values: "yes|no", CRM_destination: "nutrition.allergies", notes: "" },
  { field_key: "food_allergy_details", client_label: "Allergy details", section: "nutrition", data_type: "text", required: "conditional", possible_values: "", CRM_destination: "nutrition.allergy_details", notes: "" },
  { field_key: "dietary_restrictions", client_label: "Dietary restrictions / eating style", section: "nutrition", data_type: "json_array", required: "TRUE", possible_values: "none|vegetarian|vegan|halal|gluten_free|dairy_free|other", CRM_destination: "nutrition.restrictions", notes: "JSON array" },
  { field_key: "dietary_restriction_details", client_label: "Restriction details", section: "nutrition", data_type: "text", required: "FALSE", possible_values: "", CRM_destination: "nutrition.restriction_details", notes: "" },
  { field_key: "preferred_foods", client_label: "Foods you really enjoy", section: "nutrition", data_type: "text", required: "TRUE", possible_values: "", CRM_destination: "nutrition.preferred_foods", notes: "" },
  { field_key: "disliked_foods", client_label: "Foods you dislike or will not eat", section: "nutrition", data_type: "text", required: "TRUE", possible_values: "", CRM_destination: "nutrition.disliked_foods", notes: "" },
  { field_key: "takeout_frequency", client_label: "Restaurant / takeout frequency", section: "nutrition", data_type: "enum", required: "TRUE", possible_values: "rarely|1_2_week|3_4_week|5_plus_week", CRM_destination: "nutrition.takeout_frequency", notes: "" },
  { field_key: "water_intake", client_label: "Approximate water intake", section: "nutrition", data_type: "string", required: "TRUE", possible_values: "", CRM_destination: "nutrition.water_intake", notes: "" },
  { field_key: "alcohol_frequency", client_label: "Alcohol frequency", section: "nutrition", data_type: "enum", required: "TRUE", possible_values: "never|occasionally|weekly|multiple_times_week", CRM_destination: "nutrition.alcohol_frequency", notes: "" },
  { field_key: "weight_change_history", client_label: "Tried to lose or gain weight before", section: "nutrition", data_type: "enum", required: "TRUE", possible_values: "yes|no", CRM_destination: "nutrition.weight_change_history", notes: "" },
  { field_key: "weight_change_details", client_label: "What you tried and how it went", section: "nutrition", data_type: "text", required: "conditional", possible_values: "", CRM_destination: "nutrition.weight_change_details", notes: "" },
  { field_key: "sleep_duration", client_label: "Typical sleep", section: "lifestyle", data_type: "enum", required: "TRUE", possible_values: "under_5|5_6|6_7|7_8|8_plus", CRM_destination: "lifestyle.sleep_duration", notes: "" },
  { field_key: "sleep_quality", client_label: "Sleep quality", section: "lifestyle", data_type: "integer", required: "TRUE", possible_values: "1-5", CRM_destination: "lifestyle.sleep_quality", notes: "1 poor, 5 excellent" },
  { field_key: "stress_level", client_label: "Current stress", section: "lifestyle", data_type: "integer", required: "TRUE", possible_values: "1-5", CRM_destination: "lifestyle.stress_level", notes: "1 very low, 5 very high" },
  { field_key: "stress_sources", client_label: "Biggest sources of stress", section: "lifestyle", data_type: "text", required: "FALSE", possible_values: "", CRM_destination: "lifestyle.stress_sources", notes: "" },
  { field_key: "work_schedule", client_label: "Work schedule", section: "lifestyle", data_type: "enum", required: "TRUE", possible_values: "regular_daytime|variable|night_shifts|rotating_shifts|other", CRM_destination: "lifestyle.work_schedule", notes: "" },
  { field_key: "work_schedule_details", client_label: "Work schedule details", section: "lifestyle", data_type: "text", required: "FALSE", possible_values: "", CRM_destination: "lifestyle.work_schedule_details", notes: "" },
  { field_key: "schedule_challenges", client_label: "Schedule challenges for training consistency", section: "lifestyle", data_type: "text", required: "FALSE", possible_values: "", CRM_destination: "lifestyle.schedule_challenges", notes: "" },
  { field_key: "progress_methods", client_label: "Comfortable progress tracking methods", section: "progress", data_type: "json_array", required: "TRUE", possible_values: "see PROGRESS_METHODS", CRM_destination: "progress.methods", notes: "JSON array" },
  { field_key: "progress_photos", client_label: "Comfortable submitting private progress photos", section: "progress", data_type: "enum", required: "TRUE", possible_values: "yes|no", CRM_destination: "progress.photos_ok", notes: "Not marketing consent" },
  { field_key: "feedback_preference", client_label: "Preferred feedback", section: "coaching", data_type: "json_array", required: "TRUE", possible_values: "direct|encouraging|detailed|short_actionable|combination", CRM_destination: "coaching.feedback_preference", notes: "JSON array" },
  { field_key: "consistency_challenges", client_label: "What helps when consistency slips", section: "coaching", data_type: "text", required: "TRUE", possible_values: "", CRM_destination: "coaching.consistency_helps", notes: "Stored under PRD key consistency_challenges" },
  { field_key: "fall_off_causes", client_label: "What usually causes falling off track", section: "coaching", data_type: "text", required: "TRUE", possible_values: "", CRM_destination: "coaching.fall_off_causes", notes: "" },
  { field_key: "coaching_dislikes", client_label: "What you do not want from a coach", section: "coaching", data_type: "text", required: "FALSE", possible_values: "", CRM_destination: "coaching.dislikes", notes: "" },
  { field_key: "coaching_concerns", client_label: "Biggest nervousness or uncertainty", section: "coaching", data_type: "text", required: "TRUE", possible_values: "", CRM_destination: "coaching.concerns", notes: "" },
  { field_key: "additional_notes", client_label: "Anything else before the program is built", section: "final", data_type: "text", required: "FALSE", possible_values: "", CRM_destination: "onboarding.additional_notes", notes: "" },
  { field_key: "accuracy_acknowledgement", client_label: "Accuracy confirmation", section: "final", data_type: "boolean", required: "TRUE", possible_values: "TRUE|FALSE", CRM_destination: "onboarding.accuracy_acknowledgement", notes: "" },
  { field_key: "coach_review_needed", client_label: "Coach review needed", section: "system", data_type: "boolean", required: "TRUE", possible_values: "TRUE|FALSE", CRM_destination: "health.coach_review_needed", notes: "Review flag, not a medical assessment" },
  { field_key: "health_flag", client_label: "Health flag", section: "system", data_type: "string", required: "FALSE", possible_values: "Coach Review Needed|", CRM_destination: "health.health_flag", notes: "" },
  { field_key: "health_flag_reasons", client_label: "Health flag reasons", section: "system", data_type: "json_array", required: "FALSE", possible_values: "machine keys", CRM_destination: "health.flag_reasons", notes: "JSON array" },
  { field_key: "onboarding_status", client_label: "Onboarding status", section: "system", data_type: "string", required: "TRUE", possible_values: "submitted", CRM_destination: "onboarding.status", notes: "" },
  { field_key: "coach_notes", client_label: "Coach notes", section: "coach", data_type: "text", required: "FALSE", possible_values: "", CRM_destination: "coaching.notes", notes: "Coach-only. Stored on CLIENTS sheet." },
];
