import Link from "next/link";
import { Brand } from "@/components/product/Brand";
import { StatusBadge } from "@/components/product/ui";

export function LandingPage({ signedIn }: { signedIn: boolean }) {
 const destination = signedIn ? "/dashboard" : "/signup";
 return <div className="landing-root"><header className="marketing-nav"><Link href="/" aria-label="Coaching home"><Brand /></Link><nav aria-label="Main navigation"><a href="#approach">The approach</a><a href="#workspace">The workspace</a><a href="#connections">Connections</a></nav><div><Link className="marketing-login" href="/login">Log in</Link><Link className="button button-primary" href={destination}>{signedIn ? "Open workspace" : "Get started"}<span aria-hidden="true">↗</span></Link></div></header>
 <main><section className="marketing-hero"><div className="hero-copy"><p className="eyebrow"><span className="small-dot" /> Built for thoughtful fitness coaches</p><h1>Know the person.<br /><em>Then coach.</em></h1><p>A better beginning for every client. Build your onboarding with AI, understand their story, and start coaching with context.</p><div className="hero-actions"><Link className="button button-primary" href={destination}>Build your onboarding <span aria-hidden="true">↗</span></Link><a className="text-link" href="#approach">See how it works ↓</a></div><p className="hero-footnote">Your approach. Your questions. Always your call.</p></div><div className="hero-workspace" aria-label="Illustrative onboarding workflow"><div className="illustration-top"><Brand compact /><span>Your onboarding, taking shape</span><span className="illustration-dots">•••</span></div><div className="illustration-body"><div className="illustration-agent"><p className="eyebrow">✳ Coaching Agent</p><p className="illustration-prompt">I help busy people build confidence in the gym. Let’s start with their goals and routine.</p><p className="illustration-reply">Let’s make space for their story.</p><div className="illustration-proposal"><StatusBadge status="proposed"/><h3>A more personal beginning</h3><p>Goals &amp; motivation<br />Training experience<br />Lifestyle &amp; recovery</p><span className="illustration-applied">✓ You review every change</span></div><p className="illustration-caption">Illustrative product example</p></div><div className="illustration-form"><p className="eyebrow">Your coaching</p><span className="illustration-step">01 / Getting to know you</span><h2>What brings<br />you here?</h2><p>There’s no perfect answer.<br />Start with what matters to you.</p><div className="illustration-option selected">Build strength <span>✓</span></div><div className="illustration-option">Feel more confident <span>○</span></div><div className="illustration-option">Find a routine that fits <span>○</span></div><div className="illustration-continue">Continue <span>→</span></div></div></div></div></section>
 <div className="marketing-principles"><span>Built around your coaching</span><span>AI proposes. You decide.</span><span>A calmer client experience</span></div>
 <section id="approach" className="marketing-section approach-section"><div><p className="eyebrow">From first hello to real understanding</p><h2>A thoughtful start.<br />Without the busywork.</h2><p>Bring your coaching perspective. We’ll help you turn it into an onboarding that asks the right questions.</p></div><ol className="approach-steps"><li><span>01</span><div><h3>Tell us how you coach.</h3><p>Your coaching profile gives the Agent context about your clients and your approach.</p></div></li><li><span>02</span><div><h3>Build it together.</h3><p>Ask the Agent, review its proposed changes, and apply or reject. Refine anything yourself.</p></div></li><li><span>03</span><div><h3>Make a better first impression.</h3><p>Preview, publish, and share a calm, branded onboarding that feels natural on any device.</p></div></li><li><span>04</span><div><h3>Arrive with context.</h3><p>Read the original answers, review flagged responses, and use the AI brief to prepare.</p></div></li></ol></section>
 <section id="workspace" className="marketing-section understanding-section"><div className="understanding-example"><p className="eyebrow">Three perspectives. One clear picture.</p><article><span className="example-number">01</span><div><h3>Their own words</h3><p>Client answers stay intact, exactly as submitted.</p></div></article><article className="example-flag"><span className="example-number">02</span><div><h3>Coach review needed</h3><p>Clear, rule-based flags point to answers worth discussing.</p></div></article><article className="example-brief"><span className="example-number">03</span><div><h3>AI Coach Brief</h3><p>An organized starting point for your kickoff conversation.</p></div></article></div><div><p className="eyebrow">The human stays at the center</p><h2>More context.<br /><em>Better conversations.</em></h2><p>The Agent helps you see the story across goals, training, recovery, and preferences. Original responses remain the source of truth.</p><p>Review Flags draw your attention. They never diagnose. Your judgment leads the coaching.</p><Link className="text-link" href={destination}>Create your workspace ↗</Link></div></section>
 <section id="connections" className="marketing-section connections-section"><div><p className="eyebrow">Works with your workflow</p><h2>Your context.<br />Connected.</h2><p>Keep client records in Coaching. Send new submissions where you need them.</p></div><div className="connection-pair"><article><span className="connection-symbol">▤</span><h3>Google Sheets</h3><p>New submissions, organized in a spreadsheet. Keep your existing workflow.</p></article><article><span className="connection-symbol">⌘</span><h3>Signed webhooks</h3><p>Send structured onboarding data to your own tools. Track delivery and retry when needed.</p></article></div></section>
 <section className="marketing-cta"><p className="eyebrow">Make your next introduction count</p><h2>Better beginnings.<br /><em>Better coaching.</em></h2><Link className="button button-primary" href={destination}>Build your onboarding ↗</Link></section></main><footer className="marketing-footer"><Brand /><p>Made for the way you coach.</p><Link href="/login">Log in</Link><Link href={destination}>Get started ↗</Link></footer></div>;
}
